prefix = "." # tells MeTA where to search for datasets

dataset = "recipes" # a subfolder under the prefix directory
corpus = "tutorial.toml" # a configuration file for the corpus specifying its format & additional args

index = "recipes-idx" # subfolder of the current working directory to place index files

query-judgements = "recipes/recipes-qrels.txt" # file containing the relevance judgments for this dataset

stop-words = "stopwords.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
